### ISSUE TITLE
Missing 'unzip' command on Windows agents

### ISSUE THREAD

**Issue by ghost** [damienaicheh/azure-devops-bundletool#1]
Hi, thanks for your task ! 
I can't execute the Convert aab to universal apk task  on Windows agent because of the needs of unzip command. This command does not natively exists on Windows.

How can I handle that ?

**Comment by damienaicheh** [comment]
Hi, 3 ideas:
- You can maybe try to install the linux bash shell on your Windows agent
- Create your own script with the commands
- Use Azure DevOps online and use Linux / Mac agents

**Comment by ghost** [comment]
OK I installed 7-zip and made a batch script to create an unzip command.

Here is the code, if someone is interested in. 

```bat
7z x -y %1 -o%3
```

Just put this in a file and add its directory to your PATH.
There is no any error check and this command works for only for this case but it fits my needs.
