### ISSUE TITLE
Cannot read property browser_download_url of undefined

### ISSUE THREAD

**Issue by manojkulkarni30** [damienaicheh/azure-devops-bundletool#3]
Hi,

In latest release of bundle tool (1.5.0), jar file is not attached as an asset. Because of which the Install bundle tool task is failing with error "**Cannot read property browser_download_url of undefined**". 

Thank You.

**Comment by damienaicheh** [comment]
Hi,

An issue is opened for this: https://github.com/google/bundletool/issues/205

Hope this will be solve soon

**Comment by manojkulkarni30** [comment]
Hi @damienaicheh ,

Thank you for a quick response.

**Comment by damienaicheh** [comment]
It's online!
